### PR TITLE
removed RSVPs from past events

### PR DESCRIPTION
**Pull request by JohnClaude**

### CODE REVIEW

**Comment by nefiger** [comment]
@JohnClaude thanks for this. It looks like you are manually changing each page, is that correct? Is there not logic we can include that when the event date is passed, we make the RSVP links inactive? cc @longhotsummer

**Comment by JohnClaude** [comment]
I am thinking maybe adding a javascript function but I can't be sure at the moment. I'll take a look at it when I have some time.

**Comment by longhotsummer** [comment]
This either has to happen with javascript, or we need to trigger a rebuild of the website after an event.

**Comment by nefiger** [comment]
@longhotsummer should I merge these changes for now and we look at a javascript solution going forward?

**Comment by longhotsummer** [comment]
Ja. It's also not going to kill us to have an RSVP link to a finished meetup event. We'll be updating this site sufficiently regularly I think to have a rebuild every few days. So the cheap and dirty option is probably okay.

**Pull request merged**
